"""Claude Code validator - reads validation files generated by Claude Code."""
from pathlib import Path
from typing import Optional
import json
from loguru import logger

from .plan_reader import Step
from .deepseek_client import StepResult
from ..config.settings import settings


class ValidationResult:
    """Result of Claude Code validation."""
    
    def __init__(
        self,
        is_valid: bool,
        score: float,
        feedback: str,
        suggestions: Optional[list] = None,
        needs_correction: bool = False,
        correction_prompt: Optional[str] = None
    ):
        self.is_valid = is_valid
        self.score = score  # 0.0 to 1.0
        self.feedback = feedback
        self.suggestions = suggestions or []
        self.needs_correction = needs_correction
        self.correction_prompt = correction_prompt


class ClaudeCodeValidator:
    """
    Validates DeepSeek results by reading validation files generated by Claude Code.
    
    Workflow:
    1. DeepSeek executes step → generates output (saved to file)
    2. System indicates validation needed (logs/info)
    3. Claude Code validates → generates validation.json file
    4. System reads validation.json and requests correction if needed
    """
    
    def __init__(self, validation_dir: Optional[Path] = None):
        """
        Initialize Claude Code validator.
        
        Args:
            validation_dir: Directory where Claude Code validation files are stored
        """
        self.validation_dir = validation_dir or settings.output_dir / "validations"
        self.validation_dir.mkdir(parents=True, exist_ok=True)
    
    def should_validate(self, step: Step, result: StepResult) -> bool:
        """
        Determine if a step result should be validated.
        
        Returns False - validation is done manually by Claude Code after execution.
        """
        return False  # Pas de validation automatique, Claude Code fait manuellement
    
    def get_validation_file_path(self, step_id: str) -> Path:
        """Get path to validation file for a step."""
        return self.validation_dir / f"{step_id}_validation.json"
    
    def read_validation(self, step: Step, result: StepResult) -> Optional[ValidationResult]:
        """
        Read validation file generated by Claude Code (if exists).
        
        Args:
            step: The executed step
            result: The execution result
            
        Returns:
            ValidationResult if file exists, None otherwise
        """
        validation_file = self.get_validation_file_path(step.id)
        
        if not validation_file.exists():
            return None
        
        try:
            with open(validation_file, "r", encoding="utf-8") as f:
                validation_data = json.load(f)
            
            return ValidationResult(
                is_valid=validation_data.get("is_valid", True),
                score=float(validation_data.get("score", 0.5)),
                feedback=validation_data.get("feedback", ""),
                suggestions=validation_data.get("suggestions", []),
                needs_correction=validation_data.get("needs_correction", False),
                correction_prompt=validation_data.get("correction_prompt")
            )
            
        except (json.JSONDecodeError, KeyError, ValueError) as e:
            logger.error(f"Error reading validation file for {step.id}: {e}")
            return None
